version: 0.0.{build}
image: Visual Studio 2017 RC
init:
  - git config --global core.autocrlf true
install:
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version
before_build:
  - cmd: dotnet restore
  - cmd: npm --version
  - cmd: cd %APPVEYOR_BUILD_FOLDER%\Planner && npm install
build:
  verbosity: minimal
test_script:
  - cmd: cd %APPVEYOR_BUILD_FOLDER% && tests.bat
after_test:
  - ps: Push-AppveyorArtifact .\test-results.xml
  - ps: .\upload-results.ps1
environment:
  COVERALLS_REPO_TOKEN:
    secure: RpvJ78vABhLlkFzdKsGq5sElt1233tL2Ukh1BVsrQt+325S8BTwNHTFX/rcb2acd
  nodejs_version: "6"
