version: 0.0.{build}
image: Visual Studio 2017 RC
before_build:
  - cmd: prebuild.bat
build:
  verbosity: minimal
test_script:
  - cmd: cd %APPVEYOR_BUILD_FOLDER%
  - cmd: tests.bat
environment:
    COVERALLS_REPO_TOKEN:
        secure: RpvJ78vABhLlkFzdKsGq5sElt1233tL2Ukh1BVsrQt+325S8BTwNHTFX/rcb2acd
init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))