version: 0.0.{build}
image: Visual Studio 2017 RC
before_build:
  - cmd: dotnet restore
  - cmd: cd %APPVEYOR_BUILD_FOLDER%\Planner && npm install
  - cmd: cd %APPVEYOR_BUILD_FOLDER%\Planner && npm install
  - cmd: cd %APPVEYOR_BUILD_FOLDER%\Planner && npm install
build:
  verbosity: minimal
before_test:
  - cmd: mkdir %APPVEYOR_BUILD_FOLDER%\tools
  - cmd: mkdir %APPVEYOR_BUILD_FOLDER%\reports\coverage\history
  - cmd: cd Planner && npm install process buffer base64-js
test_script:
  - cmd: cd %APPVEYOR_BUILD_FOLDER% && powershell .\tests.ps1
  - cmd: cd %APPVEYOR_BUILD_FOLDER%\Planner && .\node_modules\.bin\karma.cmd start --single-run
after_test:
  - cmd: cd %APPVEYOR_BUILD_FOLDER% && powershell .\upload-results.ps1
environment:
    COVERALLS_REPO_TOKEN:
        secure: RpvJ78vABhLlkFzdKsGq5sElt1233tL2Ukh1BVsrQt+325S8BTwNHTFX/rcb2acd
