version: 0.0.{build}
image: Visual Studio 2017 RC
before_build:
- cmd: prebuild.bat
build:
  verbosity: minimal
before_test:
- set APPVEYOR_API_URL=
test_script:
- cmd: cd %APPVEYOR_BUILD_FOLDER%
- cmd: tests.bat
environment:
    COVERALLS_REPO_TOKEN:
        secure: RpvJ78vABhLlkFzdKsGq5sElt1233tL2Ukh1BVsrQt+325S8BTwNHTFX/rcb2acd