version: 0.0.{build}
image: Visual Studio 2017 RC
before_build:
  - ps: .\prebuild.ps1
build:
  verbosity: minimal
test_script:
  - cmd: cd %APPVEYOR_BUILD_FOLDER%
  - ps: .\tests.ps1
  - cmd: npm install process buffer
  - cmd: .\node_modules\.bin\karma.cmd start --single-run
  - ps: .\upload-results.ps1
environment:
    COVERALLS_REPO_TOKEN:
        secure: RpvJ78vABhLlkFzdKsGq5sElt1233tL2Ukh1BVsrQt+325S8BTwNHTFX/rcb2acd
